### ISSUE TITLE
app design was in wide resolution 1920x1440

### ISSUE THREAD

**Issue by shacharoz** [amsh-dev-team/Ad-Adida-Feb-2019#1]
the app is cropped in the sides on narrow phones like iphone and samsung s8
since they have resolution of 16x9

![image](https://user-images.githubusercontent.com/593642/52538933-e8688480-2d78-11e9-893b-9fa38cf7defc.png)

-----------------------------

either we change each screen or Amit provides a better design

**Comment by amirblum** [comment]
תיקנתי. הפתרון זה להשאיר את הכל כמו שהיה, פשוט להכניס קצת את הטקסט של במסך פתיחה שיהיה כמו הרפרנס. אפשר לסגור.
