### ISSUE TITLE
IronSource: ad starts to play even before the user clicks the "show ad" button

### ISSUE THREAD

**Issue by shacharoz** [amsh-dev-team/Ad-Adida-Feb-2019#2]
music start to play in this screen of the testing app (right after loading the ad)..

probably is a malfunction of the testing app.

![image](https://user-images.githubusercontent.com/593642/52538898-5d878a00-2d78-11e9-9c93-bde915577cd9.png)

**Comment by amirblum** [comment]
The fix for this is to use the "is ad viewable" in the playable plugin. I can implement this.

**Comment by amirblum** [comment]
Implemented and uploaded. Please test on your device with code t9cqoe8.

**Comment by shacharoz** [comment]
great!
