### ISSUE TITLE
Tinted colors from Construct are not working in the Ironsource ad all the time

### ISSUE THREAD

**Issue by shacharoz** [amsh-dev-team/Ad-Adida-Feb-2019#3]
it influences:
- the grass of levels, 
- the header of levels,
- the screen transition,

![image](https://user-images.githubusercontent.com/593642/52539020-d0ddcb80-2d79-11e9-84e7-a9cd89c8a3e5.png)

![image](https://user-images.githubusercontent.com/593642/52539067-29ad6400-2d7a-11e9-97a3-e1761163479e.png)

**Comment by amirblum** [comment]
This is unfortunately a restriction we were not aware of. The ironSource platform does not support WebGL, which is how the effects work in Construct.

We need to use multiple objects for each color and do some more optimizations to fit in the size. I will talk to you about this on WhatsApp.

**Comment by shacharoz** [comment]
ok i take this on me
